# Right eyebrow
r_eb_inner:
  function: map
  neutral: 0
  poly:
    # Alpha:Pos
    0:      25
    18:     50
    36:     70
    #54:     70
    #72:     70
    90:     70
    108:    50
    126:    25
    144:   -50
    162:   -50
    180:   -25
    198:    25
    216:    25
    234:   -25
    252:    25
    #270:    25
    #288:    25
    #306:    25
    324:    25
    342:    50

r_eb_outer:
  function: map
  neutral: 0
  poly:
    # Alpha:Pos
    0:      0
    18:     0
    36:     0
    54:     0
    72:     25
    90:     25
    108:    25
    126:    25
    144:    25
    162:    25
    180:    25
    198:   -25
    216:   -50
    234:   -25
    252:   -25
    270:   -25
    288:   -25
    306:    0
    324:    25
    342:    25

# Right eye
r_e_ver:
  function: eye_ver

r_e_hor:
  function: eye_hor

r_e_lid:
  function: map
  neutral: 50
  poly:
    # Alpha:Pos
    0:      50
    18:     50
    36:     50
    54:     50
    72:     50
    90:     80
    108:    80
    126:    80
    144:    50
    162:    50
    180:    50
    198:    40
    216:    40
    234:    40
    252:    25
    270:    25
    288:    50
    306:    50
    324:    50
    342:    50

# Mouth
m_l:
  function: map
  neutral: 20
  poly:
    # Alpha:Pos
    0:      50
    18:     70
    36:     70
    54:     40
    72:     0
    90:     0
    108:   -50
    126:   -50
    144:   -50
    162:   -50
    180:   -50
    198:   -100
    216:   -100
    234:   -25
    252:   -25
    270:    25
    288:    25
    306:    50
    324:    50
    342:    50

m_mid:
  function: map
  neutral: 50
  poly:
    # Alpha:Pos
    0:      100
    18:     50
    36:    -100
    54:    -100
    72:    -50
    90:    -100
    108:   -80
    126:   -80
    144:   -80
    162:    50
    180:    100
    198:    100
    216:    100
    234:    100
    252:    100
    270:    100
    288:    100
    306:    100
    324:    100
    342:    100

m_r:
  function: map
  neutral: 20
  poly:
    # Alpha:Pos
    0:      50
    18:     70
    36:     70
    54:     40
    72:     0
    90:     0
    108:   -50
    126:   -50
    144:   -50
    162:   -50
    180:   -50
    198:   -100
    216:   -100
    234:   -25
    252:   -25
    270:    25
    288:    25
    306:    50
    324:    50
    342:    50

# Left eye
l_e_lid:
  function: map
  neutral: 50
  poly:
    # Alpha:Pos
    0:      50
    18:     50
    36:     50
    54:     50
    72:     50
    90:     80
    108:    80
    126:    80
    144:    50
    162:    50
    180:    50
    198:    40
    216:    40
    234:    40
    252:    25
    270:    25
    288:    50
    306:    50
    324:    50
    342:    50

l_e_ver:
  function: eye_ver

l_e_hor:
  function: eye_hor

# Left eyebrow
l_eb_inner:
  function: map
  neutral: 0
  poly:
    # Alpha:Pos
    0:      25
    18:     50
    36:     70
    54:     70
    72:     70
    90:     70
    108:    50
    126:    25
    144:   -50
    162:   -50
    180:   -25
    198:    25
    216:    25
    234:   -25
    252:    25
    270:    25
    288:    25
    306:    25
    324:    25
    342:    50

l_eb_outer:
  function: map
  neutral: 0
  poly:
    # Alpha:Pos
    0:      0
    18:     0
    36:     0
    54:     0
    72:     25
    90:     25
    108:    25
    126:    25
    144:    25
    162:    25
    180:    25
    198:   -25
    216:   -50
    234:   -25
    252:   -25
    270:   -25
    288:   -25
    306:    0
    324:    25
    342:    25
