# Right eyebrow
0:  r_eb_inner
1:  r_eb_outer

# Right eye
2:  r_e_ver
3:  r_e_hor
4:  r_e_lid

# Mouth
5:  m_l
6:  m_mid
7:  m_r

# Left eye
11: l_e_lid
12: l_e_ver
13: l_e_hor

# Left eyebrow
14: l_eb_inner
15: l_eb_outer
